[package]
name = "absal"
version = "0.1.3"
authors = ["Victor Maia <srvictormaia@gmail.com>"]
description = "Optimal reduction of Î»-terms"
license = "MIT"

[lib]
name = "absal"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
